runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: index.app

- url: /(.+)/
  static_files: dist/\1/index.html
  upload: dist/(.*)

- url: /assets
  static_dir: dist/assets
  application_readable: true

- url: /
  static_dir: dist/
  application_readable: true
libraries:
- name: flask
  version: latest
