runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.+)/
  static_files: dist/\1/index.html
  upload: public/(.*)
- url: /(.+)
  static_dir: dist/
  application_readable: true
- url: /
  script: index.app
libraries:
- name: flask
  version: latest
